<a href="https://colab.research.google.com/github/ShivaniMareddy/Numpy/blob/main/Numpy(TekAIDS).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr_1d=np.array([1,2,3])
print(arr_1d)

[1 2 3]


In [5]:
import numpy as np
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np
arr_0d=np.array(52)
arr_1d=np.array([1,2,3])
arr_2d=np.array([[1,2,3],[4,5,6]])
arr_3d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(arr_0d.ndim)
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

0
1
2
3


In [13]:
#array of zeros
zeros=np.zeros((2,3))
print(zeros)

#array of ones
ones=np.ones((3,3))
print(ones)

#array of random
random_arr=np.random.random((2,2))
print(random_arr)

#identity
identity=np.eye(3)
print(identity)

#Array with a range of values
range_arr=np.arange(0,10,2)#Start,Stop,Step
print(range_arr)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0.56023003 0.49656138]
 [0.49766717 0.80131428]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]


In [14]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Data Type:",arr.dtype)
print("Number of Dimensions:",arr.ndim)

Shape: (2, 3)
Size: 6
Data Type: int64
Number of Dimensions: 2


You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.

Each greenhouse has sensors that record temperature (°C) readings at different times of the day.
You received the following data:
Your tasks are:
Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.
Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.
Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.
Generate supporting data
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
Display all arrays
Print updated_temp_data, sensor_error_flags, and greenhouse_identity.

In [19]:
temp_data=np.array([[22,25,20],[24,26,23]])
print("Temperature Data:",temp_data)
print("Shape:",temp_data.shape)
print("Size:",temp_data.size)
print("Data Type:",temp_data.dtype)
print("Number of Dimensions:",temp_data.ndim)
updated_temp_data=np.array([[22,25,20],[24,26,23],[21,23,22]])
sensor_error_flags=np.zeros((2,3))
greenhouse_identity=np.eye(3)
print("Updated Temperature data:",updated_temp_data)
print("Sensor Error flags:",sensor_error_flags)
print("Identity:",greenhouse_identity)


Temperature Data: [[22 25 20]
 [24 26 23]]
Shape: (2, 3)
Size: 6
Data Type: int64
Number of Dimensions: 2
Updated Temperature data: [[22 25 20]
 [24 26 23]
 [21 23 22]]
Sensor Error flags: [[0. 0. 0.]
 [0. 0. 0.]]
Identity: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
#Indexing and Slicing
arr=np.array([[10,20,30],[40,50,60]])
print(arr[0,1])
print(arr[1,2])
print(arr[1,0])
#Slicing
print(arr[:1])
print(arr[1:])
print(arr[0::2])

20
60
40
[[10 20 30]]
[[40 50 60]]
[[10 20 30]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.

The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).

Your Tasks
Create the 2D NumPy array

Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.


In [41]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print("Shipments:",shipments)
print("Apples shipped on Wednesday:",shipments[0,2])
print("Oranges shipped on Sunday:",shipments[1,6])
print("Weekday shipments (Mon–Fri) for all fruits.",shipments[0:2,0:5])
print("Weekend shipments (Sat & Sun).",shipments[0:2,5:7])
print("Apples from Wednesday to Saturday.",shipments[0,2:6])
shipments[0,5]=100
print("Shipments:",shipments)

Shipments: [[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]
Apples shipped on Wednesday: 55
Oranges shipped on Sunday: 75
Weekday shipments (Mon–Fri) for all fruits. [[50 60 55 70 65]
 [40 45 50 60 55]]
Weekend shipments (Sat & Sun). [[80 90]
 [70 75]]
Apples from Wednesday to Saturday. [55 70 65 80]
Shipments: [[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


Array Operations

In [45]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition",a+b)
print("Subtraction",a-b)
print("Multiplication",a*b)
print("Division",a/b)
print("Scalar",a*2)
print("floor division",a//b)
#matrix operations
mat1=np.array([[1,2],[5,7]])
mat2=np.array([[4,5],[8,9]])
print("Matrix Addition",mat1+mat2)
print("Matrix Difference",mat1-mat2)
pro=np.dot(mat1,mat2)
print("Multiplication",pro)

Addition [5 7 9]
Subtraction [-3 -3 -3]
Multiplication [ 4 10 18]
Division [0.25 0.4  0.5 ]
Scalar [2 4 6]
floor division [0 0 0]
Matrix Addition [[ 5  7]
 [13 16]]
Matrix Difference [[-3 -3]
 [-3 -2]]
Multiplication [[20 23]
 [76 88]]


Broadcasting:
Numpy automatically applies operations across arrays of different shapes when compatible

In [46]:
a=np.array([1,2,3])
b=2
print(a+b)

[3 4 5]


Universal Functions
. Arithmetic ufuncs
Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)
🔹 2. Exponential and Logarithmic ufuncs
(You already covered these)
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1
🔹 3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)
🔹 4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)
🔹 5. Statistical ufuncs
(Operate along an axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)
🔹 6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)
🔹 7. Comparison ufuncs
(Return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)
🔹 8. Bitwise ufuncs
(Operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)

In [50]:
arr=np.array([1,2,3])
print(np.exp(arr))
print(np.sqrt(arr))
print(np.log(arr))
print(np.power(arr,2))
print(np.sin(arr))
arr2=np.array([5.8,6.3,9.7])
print(np.round(arr2))
print(np.floor(arr2))

[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[1 4 9]
[0.84147098 0.90929743 0.14112001]
[ 6.  6. 10.]
[5. 6. 9.]


Aggregate Functions

In [53]:
arr=np.array([1,2,3,4])
print("Array:",arr)
print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Standard Deviation:",np.std(arr))
print("Max:",np.max(arr))
print("Min:",np.min(arr))

Array: [1 2 3 4]
Sum: 10
Mean: 2.5
Standard Deviation: 1.118033988749895
Max: 4
Min: 1


You are a data engineer at a renewable-energy company that runs 3 solar farms.

 Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):

Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)

 Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.


In [82]:
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
production_all=np.stack((farmA,farmB,farmC),dtype=float)
print("Production",production_all)
print("Shape",np.shape(production_all))
print("Size",np.size(production_all))
print("DType",production_all.dtype)
print("No of dim",np.ndim(production_all))
total_per_farm=np.sum(production_all,axis=(1,2))
print("Total Per farm",total_per_farm)
print("Mean",np.mean(production_all,axis=(1,2)))
print("Standard Deviation",np.std(production_all,axis=(1,2)))
print("Variance",np.var(production_all,axis=(1,2)))
hour_weights = np.array([0.5, 1.0, 0.75])
weighted_per_panel = np.dot(production_all, hour_weights)
print("Weighted per-panel production (3 farms × 4 panels):\n", weighted_per_panel)
print("\nShape:", weighted_per_panel.shape)
production_all[1]+=0.5
print("Updated Production",production_all)
farm_means=np.mean(production_all,axis=(1,2))
farm_std=np.std(production_all,axis=(1,2))
normalized=(production_all-farm_means)/farm_std
print("Normalized",normalized)
print(np.exp(normalized))
print(np.expm1(normalized))
print(np.cos(normalized))
print(np.tan(normalized))

print(np.degrees(normalized))
print(np.radians(normalized))
print(np.round(normalized))
print(np.floor(normalized))
print(np.ceil(normalized))
print(np.trunc(normalized))
high_output = production_all > 20
print("High Output:\n", high_output)
even_hours_mask = np.array([False, True, False])
and_mask = np.logical_and(high_output, even_hours_mask)
and_mask = np.logical_and(high_output, even_hours_mask)
or_mask  = np.logical_or(high_output, even_hours_mask)
not_mask = np.logical_not(high_output)
xor_mask = np.logical_xor(high_output, even_hours_mask)

print("\nLogical AND (high & even-hour):\n", and_mask)
print("\nLogical OR (high | even-hour):\n", or_mask)
print("\nLogical NOT (not high output):\n", not_mask)
print("\nLogical XOR (exclusive high/even):\n", xor_mask)
greater_equal_mask = np.greater_equal(production_all, 20)
less_mask = np.less(production_all, 18)

print("\nGreater or Equal to 20:\n", greater_equal_mask)
print("\nLess than 18:\n", less_mask)
alerts = np.array([
    [[1,0,1],
     [0,0,1],
     [1,1,0],
     [0,1,0]],

    [[0,1,1],
     [1,0,0],
     [0,1,1],
     [1,1,0]],

    [[1,1,0],
     [0,0,1],
     [1,1,1],
     [0,1,0]]
], dtype=int)

bit_and = np.bitwise_and(alerts[0], alerts[1])
bit_or  = np.bitwise_or(alerts[1], alerts[2])
bit_not = np.invert(alerts[2])

print("\nBitwise AND (FarmA & FarmB):\n", bit_and)
print("\nBitwise OR (FarmB | FarmC):\n", bit_or)
print("\nBitwise NOT (~FarmC):\n", bit_not)
# Arithmetic ufuncs on production_all
added      = np.add(production_all, 2)
subtracted = np.subtract(production_all, 1)
multiplied = np.multiply(production_all, 1.1)
divided    = np.divide(production_all, 2)
powered    = np.power(production_all, 2)
modded     = np.mod(production_all, 5)

print("\nAdded (+2):\n", added[0])
print("\nDivided by 2:\n", divided[2])

# Aggregation over ufunc results
exp_sum  = np.sum(np.exp(production_all / 10))
sin_mean = np.mean(np.sin(production_all))

print("\nSum of exp(production_all/10):", exp_sum)
print("Mean of sin(production_all):", sin_mean)
panel_totals_per_farm = np.sum(production_all, axis=2)
print("Panel Totals per Farm (3×4):\n", panel_totals_per_farm)
needs_maintenance = np.any(panel_totals_per_farm < 40, axis=1)
print("\nNeeds Maintenance (3,):\n", needs_maintenance)
min_per_farm = np.min(panel_totals_per_farm, axis=1)
max_per_farm = np.max(panel_totals_per_farm, axis=1)
any_below_40 = np.any(panel_totals_per_farm < 40, axis=1)
all_above_40 = np.all(panel_totals_per_farm >= 40, axis=1)

summary_table = np.vstack([min_per_farm, max_per_farm, any_below_40, all_above_40]).T
print("\nBroadcast-based Summary Table (per Farm):")
print("Columns = [Min_Total, Max_Total, Any_Below_40, All_Above_40]\n")
print(summary_table)
# a) Overall total
overall_total = np.sum(production_all)

# b) Peak hour (max value) and its position
peak_value = np.max(production_all)
peak_index = np.unravel_index(np.argmax(production_all), production_all.shape)
peak_farm, peak_panel, peak_hour = peak_index

# c) Average per panel
average_per_panel = np.mean(panel_totals_per_farm)

print("\n--- FINAL KPIs ---")
print(f"Overall Total Energy Output: {overall_total:.2f} kWh")
print(f"Peak Hour Value: {peak_value:.2f} kWh (Farm {peak_farm}, Panel {peak_panel}, Hour {peak_hour})")
print(f"Average Production per Panel: {average_per_panel:.2f} kWh")


Production [[[10. 12. 11.]
  [ 9. 11. 10.]
  [12. 13. 14.]
  [ 8.  7.  9.]]

 [[20. 19. 21.]
  [18. 20. 19.]
  [22. 23. 21.]
  [17. 18. 16.]]

 [[15. 16. 14.]
  [14. 13. 15.]
  [16. 17. 18.]
  [12. 11. 13.]]]
Shape (3, 4, 3)
Size 36
DType float64
No of dim 3
Total Per farm [126. 234. 174.]
Mean [10.5 19.5 14.5]
Standard Deviation [1.97905701 1.97905701 1.97905701]
Variance [3.91666667 3.91666667 3.91666667]
Weighted per-panel production (3 farms × 4 panels):
 [[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]

Shape: (3, 4)
Updated Production [[[10.  12.  11. ]
  [ 9.  11.  10. ]
  [12.  13.  14. ]
  [ 8.   7.   9. ]]

 [[20.5 19.5 21.5]
  [18.5 20.5 19.5]
  [22.5 23.5 21.5]
  [17.5 18.5 16.5]]

 [[15.  16.  14. ]
  [14.  13.  15. ]
  [16.  17.  18. ]
  [12.  11.  13. ]]]
Normalized [[[-0.25264558 -4.04232922 -1.76851903]
  [-0.75793673 -4.54762037 -2.27381019]
  [ 0.75793673 -3.53703807 -0.25264558]
  [-1.26322788 -6.56878498 -2.77910134]]

 [[ 5.0529115

Reshape

In [78]:
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


Stacking and Splitting


In [84]:
a=np.array([1,2])
b=np.array([3,4])
print(np.vstack((a,b)))
print(np.hstack((a,b)))
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,3))
print(np.array_split(arr,7))

[[1 2]
 [3 4]]
[1 2 3 4]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64)]


Adcanced Indexing

In [85]:
#boolean indexing
arr=np.array([1,2,3,4,5])
print(arr[arr>3])
#fancy indexing
arr=np.array([10,20,30,40])
indices=[0,2]
print(arr[indices])

[4 5]
[10 30]


Copy vs View

In [92]:
#view shares memory
arr=np.array([1,2,3])
view=arr.view()
view[0]=10
print(arr)
#copy does not share memory
copy=arr.copy()
copy[0]=50
print(arr)

[10  2  3]
[10  2  3]


Saving and Loading

In [94]:
arr=np.array([1,2,3])
np.save('array.npy',arr)
loaded_arr=np.load('array.npy')
print(loaded_arr)

[1 2 3]


TasksArray Creation
Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [135]:
#Array with a range of values
range_arr=np.arange(10,51)#Start,Stop,Step
print(range_arr)
random_arr=np.random.random((3,3))
print(random_arr)
print("Shape",np.shape(range_arr))
print("Size",np.size(range_arr))
print("DataType",range_arr.dtype)
arr=np.array([1,2,3,4,5])
arr+=5
print(arr)
mat1=np.array([[1,2],[3,4]])
may2=np.array([[5,6],[7,9]])
mul=np.dot(mat1,mat2)
print(mul)
array=np.arange(1,26)
reshaped=array.reshape(5,5)
print(reshaped)
print(reshaped[0])
print(reshaped[:,4])
print(reshaped[0:3,0:2])
rand= np.random.randint(10, 101, size=10)
print(rand)
print("Max",np.max(rand))
print("Min",np.min(rand))
print("Mean",np.mean(rand))
print("Standard Deviation",np.std(rand))
arr2=np.arange(1,13)
print(arr2)
print(arr2.reshape(3,4))
ones=np.ones((3,3))
print(ones)
ones[:,]+=[1,2,3]
print(ones)
rand2= np.random.randint(1,50,10)
print(rand2)
print(rand2[rand2%5==0])
#fancy indexing
arr3=np.array([[10,20,30,40],[78,56,23,12],[90,67,15,63],[15,86,92,26]])
print(arr3)
diagonals=arr3[np.arange(4),np.arange(4)]
print("Diagonal elements",diagonals)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.41962202 0.61857807 0.77397015]
 [0.47301595 0.36836891 0.35795999]
 [0.0103694  0.71383294 0.15221268]]
Shape (41,)
Size 41
DataType int64
[ 6  7  8  9 10]
[[20 23]
 [44 51]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]
[38 17 28 16 23 41 52 37 33 66]
Max 66
Min 16
Mean 35.1
Standard Deviation 14.767870530310049
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
[38 40 30 10 46 19 22 25  5 44]
[40 30 10 25  5]
[[10 20 30 40]
 [78 56 23 12]
 [90 67 15 63]
 [15 86 92 26]]
Diagonal elements [10 56 15 26]
